events {
    worker_connections 1024;
}

http {
    # Сервис SupportPulse
    server {
        listen 80;
        server_name app.mysite.com; # Твой домен

        location / {
            proxy_pass http://supportpulse:8000; # Имя сервиса из docker-compose
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # Сюда потом добавишь конфиг для бота
}